apiVersion: placement.kubernetes-fleet.io/v1beta1
kind: ResourceOverride
metadata:
  name: per-cluster-override
spec:
  placement:
    name: kustomized-ngix
  policy:
    overrideRules:
    - clusterSelector:
        clusterSelectorTerms: []
      jsonPatchOverrides:
      - op: replace
        path: /spec/path
        value: ./kustomize-nginx/overlays/${MEMBER-CLUSTER-NAME}
      - op: replace
        path: /spec/suspend
        value: false
  resourceSelectors:
  - group: kustomize.toolkit.fluxcd.io
    kind: Kustomization
    name: kustomize-nginx
    version: v1