apiVersion: placement.kubernetes-fleet.io/v1beta1
kind: ResourcePlacement
metadata:
  name: kustomized-ngix
spec:
  resourceSelectors:
    - group: kustomize.toolkit.fluxcd.io
      kind: Kustomization
      name: guestbook-kustomize
      version: v1
    - group: source.toolkit.fluxcd.io
      kind: GitRepository
      name: guestbook-kustomize
      version: v1
  policy:
    placementType: PickAll
  strategy:
    type: External
