resources:
  - namespace.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - git-repository.yaml
  - kustomization-nginx-application.yaml
  - application-override.yaml
  - application-placement.yaml
  - nginx-ns-placement.yaml
  - updateRun.yaml
  - updateStrategy.yaml

namespace: nginx-demo